openapi: 3.0.0
info:
  title: API
  version: 1.0.0
paths:
  /users:
    get:
      summary: Get all users
      tags:
        - users
      responses:
        '200':
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Users'
    post:
      summary: Create a new User
      tags:
        - users
      requestBody:
        description: Data User to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '201':
          description: Created User
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
  /users/{id}/tasks:
    get:
      summary: Getting tasks from a specific user.
      tags: [ users ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer

      responses:
        '200':
          description: A list of user's tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RequestBodyTask'

  /users/{id}:
    patch:
      summary: Change username
      tags: [users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Users'
      responses:
        '200':
          description: User updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
    delete:
      summary: Delete a User
      tags: [ users ]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted

components:
  schemas:
    Users:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        password:
          type: string
    RequestBodyTask:
      type: object
      properties:
        id:
          type: integer
        task:
          type: string
        user_id:
          type: integer